# Generated by Django 3.0.6 on 2020-05-15 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0002_auto_20200515_1913'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paciente',
            old_name='nome',
            new_name='_nome',
        ),
    ]
