# Generated by Django 3.0.6 on 2020-05-15 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0003_auto_20200515_1930'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paciente',
            old_name='_nome',
            new_name='nome',
        ),
    ]
