# Generated by Django 3.0.6 on 2020-05-19 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0004_auto_20200515_1934'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paciente',
            old_name='nascionalidade',
            new_name='nacionalidade',
        ),
    ]
