# Generated by Django 3.0.6 on 2020-05-19 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0005_auto_20200519_2017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='telefone',
        ),
    ]
