# Generated by Django 3.0.6 on 2020-05-20 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exames', '0004_exame__diagnostico'),
        ('consultas', '0001_initial'),
        ('pacientes', '0008_idade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Especial',
            fields=[
                ('paciente_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pacientes.Paciente')),
                ('is_especial', models.BooleanField(default=True, verbose_name='especial')),
                ('info_especial', models.TextField(blank=True, max_length=500, null=True, verbose_name='Informações Especial')),
            ],
            bases=('pacientes.paciente',),
        ),
        migrations.DeleteModel(
            name='Idade',
        ),
    ]
