# Generated by Django 3.0.6 on 2020-05-20 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0009_auto_20200520_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='idade',
            field=models.PositiveIntegerField(choices=[(1, 'Criança'), (2, 'Jovem'), (3, 'Adulto'), (4, 'Idoso')], default=1, verbose_name='Idade Pessoa Especial'),
        ),
    ]
