# Generated by Django 3.0.6 on 2020-05-16 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0004_auto_20200515_1934'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_tipo', models.PositiveIntegerField(choices=[(1, 'Urina'), (2, 'Sangue'), (3, 'Vista')], default=2, verbose_name='tipo de exame')),
                ('data_entrega', models.DateTimeField(blank=True, null=True, verbose_name='data de entrega')),
                ('exame_paciente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pacientes.Paciente', verbose_name='nome do paciente')),
            ],
        ),
    ]
