# Generated by Django 3.0.6 on 2020-05-19 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exames', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exame',
            name='data_entrega',
        ),
    ]
