# Generated by Django 3.0.6 on 2020-05-20 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exames', '0003_exame__grau'),
    ]

    operations = [
        migrations.AddField(
            model_name='exame',
            name='_diagnostico',
            field=models.PositiveIntegerField(choices=[(1, 'Saudavel'), (2, 'Medio'), (1, 'Doente')], default=1, verbose_name='Diagnostico do Exame'),
        ),
    ]
