# Generated by Django 3.0.6 on 2020-05-15 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0004_auto_20200515_1934'),
        ('funcionarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField(blank=True, max_length=200, null=True, verbose_name='motivo da consulta')),
                ('data_consulta', models.DateTimeField(blank=True, null=True, verbose_name='agendada para:')),
                ('nome', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pacientes.Paciente', verbose_name='nome do paciente')),
                ('nome_medico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='funcionarios.Medico', verbose_name='nome do médico')),
            ],
        ),
    ]
